# Generated by Django 3.2 on 2021-04-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210426_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommentmodel',
            name='comment_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
