# Generated by Django 3.2 on 2021-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postcommentmodel_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmodel',
            name='comment_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
